version: '3'

services:
  flask:
    build : .
    restart: always
    ports:
      - '5000:${PORT}'
    volumes:
      - ./FlaskApp:/app
    working_dir: /app
    depends_on:
      - mongo 
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:${MONGO_PORT}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    env_file:
      - .env

volumes:
  data:
  node_modules:
